### ISSUE TITLE
Lift List Can't Sort In Number Order, Ascending and Descending. [Improvement]

### ISSUE THREAD

**Issue by ZaineJJ** [softlong/LiftProf#33]
LP > Main Page > Lift List 
The Lift List can't be sort by Ascending / Descending Orders therefore it is confusing. It is based on LG's Lift List order. So this can be improved.

Add in a button for Sorting Order Button for Lift Name going by Splendour-0101 > ....-0102 > ....-0103 and so on.

**Comment by shengyiHuang** [comment]
已解决
